baseURL = 'https://crl-tuebingen-2023.github.io/'
canonifyurls = true
languagecode = "en"
theme = "crl-tuebingen-2023-theme"
disableKinds = ["taxonomyTerm"]


# Params that are used in <head>
[params]
  supertitle = "Workshop on"
  title = "Causal Representation Learning"
  subtitle = "April 17-19 2023 @ MPI-IS Tuebingen"
  description = "Workshop on Causal Representation Learning 2023 in Tuebingen"
  keywords = ["workshop", "causal representation learning"]

# Options for Markdown renderer
[markup.goldmark.renderer]
  unsafe = true
  xHTML = true

# Main menu
[[menu.main]]
    name = "About"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "Schedule"
    url  = "/schedule"
    weight = 2
[[menu.main]]
    name = "Speakers"
    url  = "/speakers"
    weight = 3
[[menu.main]]
    name = "Organisers"
    url  = "/organisers"
    weight = 4
[[menu.main]]
    name = "Location"
    url  = "/location"
    weight = 5